### ISSUE TITLE
iap API: propagate errors that originate from the stores (App Store, Google Play etc...) to the callback (DEF-2644) 

### ISSUE THREAD

**Issue by AGulev** [defold/extension-iap#2]
WHY
So in dksdk that tracking ExternalStorePurchaseError will have more specific error codes / values, like it does in KSDK, and Blossom Blast game is really pushing for this.

Proposed solution from [~daniel.ekstrom]:
Just add the error code in the error table. I think that there will be a lot of enums for both Android/iOS, and they might change over the different versions.

It would be good to have examples of the values of the error code for our tests,
are they numbers and and do they have specific range, or are they strings.

**Comment by britzl** [comment]
We've added several new error codes since this ticket was opened:

https://github.com/defold/extension-iap/blob/master/extension-iap/src/java/com/defold/iap/IapJNI.java#L12-L20

I'm closing this issue. Please add new tickets for specific errors that are not surfaced to Lua.
