### ISSUE TITLE
acknowledgePurchase() on Android for permanent IAP

### ISSUE THREAD

**Issue by subsoap** [defold/extension-iap#21]
I got a message on on the console 

```
We’ve detected that your package com.curtiscollins.classytaxi is not always acknowledging in-app purchases or subscriptions. Starting with Billing Library 2.0, all purchases must be acknowledged within 3 days or they will be automatically refunded. Learn more
```
The package name is not one of my apps https://www.reddit.com/r/androiddev/comments/fh0t97/anybody_else_getting_a_weird_google_play_console/ but it made me look into their requirements and I am not sure if acknowledgePurchase() is being called. So it is probably a function that needs to be added for those of us with permanent IAPs that are not consumed on Android.

https://developer.android.com/google/play/billing/billing_library_overview#acknowledge

**Comment by AGulev** [comment]
This is Google Console bug, a lot of people got this message with the same package name (I had one too)
Now this message disappeared

**Comment by subsoap** [comment]
Yes, but it's possible they were testing something that targeted devs who have permanent IAPs that are not being consumed. I have multiple Google Play accounts and I noticed that the message only showed up on an account with games with permanent IAPs that are not consumed, not on another account with zero IAPs in games at all.

**Comment by subsoap** [comment]
Probably would want isAcknowledged() too to verify.

**Comment by AGulev** [comment]
In my opinion, we shouldn't fix the non-existent problem. 
If something like that happens then it makes sence to increase the priority of Android Billing 2.0  
imho

**Comment by subsoap** [comment]
If this is not Billing 2.0 already then those features don't apply? Then there should be nothing to worry about for now.

**Comment by britzl** [comment]
I agree that we should close this issue. But I also want to point out that adding support for Billing 2.0 is going to be prioritised by us this spring.
