### ISSUE TITLE
Android Crash (IapGooglePlay.java:135)

### ISSUE THREAD

**Issue by AGulev** [defold/extension-iap#24]
```
java.lang.NullPointerException: 
  at com.defold.iap.IapGooglePlay$SkuDetailsThread.run (IapGooglePlay.java:135)
```
<img width="939" alt="image" src="https://user-images.githubusercontent.com/2209596/87086158-71674200-c231-11ea-838b-b9a6ea6cd787.png">

https://github.com/defold/extension-iap/blob/fcbdd9f4a6116029087ea44e6d9cc9730accf5fa/extension-iap/src/java/com/defold/iap/IapGooglePlay.java#L135

**Comment by britzl** [comment]
Hmm, why would that line generate a npe? If `service` is null it should have failed a few lines above: https://github.com/defold/extension-iap/blob/fcbdd9f4a6116029087ea44e6d9cc9730accf5fa/extension-iap/src/java/com/defold/iap/IapGooglePlay.java#L132

Any ideas?

**Comment by AGulev** [comment]
yes, I thought about it. It's really strange. maybe something wrong with the call stack...

**Comment by AGulev** [comment]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/2209596/87090851-f30e9e00-c238-11ea-9da3-e91d419fe693.png">

**Comment by britzl** [comment]
We could add a check to see if `service` is null and log that maybe and watch your numbers to see if it helps.

**Comment by britzl** [comment]
This code has been completely rewritten with the migration to Billing 3.0
