### ISSUE TITLE
External store purchase interruption causes the item to not be purchasable again (DEF-3641)

### ISSUE THREAD

**Issue by AGulev** [defold/extension-iap#4]
Description:
So after getting interrupted during the purchase from the native store we get into a strange stage. The store does not give us anything in the iap_listener but we cannot rebuy the product.

Puzzle setting that might be of use for the person that is going to test this:
[iap]
auto_finish_transactions = 0

Steps to reproduce:

Start puzzle.
Buy a gold bar package.
When after you bought it but before you got the native dialog confirmation turn off the internet.
Enable the internet again and try to buy the product
Restart the app again check the iap_listener
Expected result:
A few things that i would expect would be ok:

1: it was just canceled so we can just rebuy the product, the store does not have an unfinished transaction cause it was canceled.

2:The transaction was actually created on the external store but we did not have internet to get the result. Then our iap_listener can now finish the purchase using the transaction and adding that to the purchase and calling perform_mercado_purchase.

Actual result:
We do not get anything in the iap_listener on startup.
We cannot rebuy the product ERROR:IAP: IAP error 7 which i do think is BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED.

Some logs:

When we lose internet the iap_handler says this, the result of use turning off the internet:

DEBUG: [IAP_HANDLER] buy() error	nil	{
11-21 15:18:40.980 15090 15106 D defold : "error" = "user canceled purchase"
11-21 15:18:40.980 15090 15106 D defold : "reason" = 1
11-21 15:18:40.980 15090 15106 D defold : }

That means that the transaction is nil and the error message can be seen

When trying to rebuy the same product this happens

ERROR:IAP: IAP error 7
11-21 15:23:02.451 16231 16246 D defold : DEBUG:SCRIPT: INFO : DEBUG: [IAP_HANDLER] buy() error	nil	{
11-21 15:23:02.451 16231 16246 D defold : "error" = "failed to buy product"
11-21 15:23:02.451 16231 16246 D defold : "reason" = 0
11-21 15:23:02.451 16231 16246 D defold : }
2019-01-15 14:27:27 (Bjorn.Ritzl)
The Store Module in Game Platform seems to handle this case quite a bit differently:

It seems like when it gets an ITEM_ALREADY_OWNED error it searches through previous purchases and returns the one matching the current purchase.

**Comment by britzl** [comment]
The purchase flow and the way interruptions are handled has been changed significantly with Billing 3.0. Closing.
