### ISSUE TITLE
Android Crash: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by SkaterDad** [defold/extension-iap#47]
I've seen this crash recently in the Play Console.  Only 12 occurrences and 10 users, thankfully.

Devices are a mix of random Chinese phones & low end Samsung & Nokia.  Android 8.1, 9, 10, 11. 

All of these crashes occurred on the Instant release, so maybe it's something Google screwed up in their wrapping code.

```
java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:437)
  at com.defold.iap.IapGooglePlay$5.onSkuDetailsResponse (IapGooglePlay.java:343)
  at com.defold.iap.IapGooglePlay$6.onSkuDetailsResponse (IapGooglePlay.java:376)
  at com.android.billingclient.api.zzj.run
  at android.os.Handler.handleCallback (Handler.java:888)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:213)
  at android.app.ActivityThread.main (ActivityThread.java:8178)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
```

The issue seems to be here:
https://github.com/defold/extension-iap/blob/master/extension-iap/src/java/com/defold/iap/IapGooglePlay.java#L343-L344

Kind of odd that `Get(0)` would fail after the `if` statement does null & empty checks.

**Comment by britzl** [comment]
Interesting. I wouldn't think that could happen.... One things to try is to make a copy of the skuDetailsList to ensure that no one else is messing with it from another thread or something, but it seems like a very unlikely thing to happen.

Very wild guess but it could be someone hacking your game...

**Comment by SkaterDad** [comment]
> Very wild guess but it could be someone hacking your game...

I suppose that is possible.  It's less than 0.01% of the players, so perhaps it's not worth investigating this any further.

This just happened to be the one crash which had a useful stack trace.

**Comment by britzl** [comment]
It might be worth looking into still! My recommendation of copying the list before checking size and getting the first item should be a quick way of ensuring that nothing is tampering with the list in between those two lines of code.

**Comment by JCash** [comment]
> a quick way of ensuring that nothing is tampering with the list in between those two lines of code.

If that's the issue, then that might just as well happen while you're copying the data, right?
Which would produce similarly strange results?

Is there a recommended way of doing this? E.g. is there an example app from Google which we could adopt best practices from? Perhaps we're using an old recommended way?

**Comment by britzl** [comment]
> If that's the issue, then that might just as well happen while you're copying the data, right?
> Which would produce similarly strange results?
> 
> Is there a recommended way of doing this? E.g. is there an example app from Google which we could adopt best practices from? Perhaps we're using an old recommended way?

Good point! Here's the official example from Google:

https://github.com/android/play-billing-samples/blob/main/TrivialDriveJava/app/src/main/java/com/sample/android/trivialdrivesample/billing/BillingDataSource.java#L363-L382

Things to note: We only care about the first result, hence the get(0). BUT maybe we should use a `for (SkuDetails skuDetails : skuDetailsList)` and use the first skuDetails instead? It doesn't really solve anything though... (except not throw a IndexOutOfBoundsException)
