### ISSUE TITLE
From November 1, 2022, all app updates must use Billing Library version 4 or newer.

### ISSUE THREAD

**Issue by Dr-Klaus** [defold/extension-iap#51]
The extension must be updated to Google Billing Library version 4 (or 5) by November 1, 2022 or earlier.
Thanks!!!
<img width="580" alt="image" src="https://user-images.githubusercontent.com/87762110/188264314-df84d639-6136-4717-bb8d-0b023cdbd04f.png">

**Comment by AGulev** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/2209596/188264711-17232f97-80e9-4c46-b72c-4fd66f1739d3.png">
I think it worth to migrate billing 5 (the latest at the moment)
https://developer.android.com/google/play/billing/migrate-gpblv5
