### ISSUE TITLE
Update Android Play Billing Library

### ISSUE THREAD

**Issue by AGulev** [defold/extension-iap#61]
message in google play:

Android 14 has introduced new [security changes](https://notifications.google.com/g/p/ANiao5o2037_oMi178DOp_mL3eGTrzo_pP4uR7uaPzsmF9mhy73YA9rTUSULMW-o10aOkYe-wnt-Lymc6XayEf0DExrt-7mRfGOMvkMKvQ130Q5cPoZpmH7WlNm-lZ09JYBtQ7BW1c-snRxrQzb4D6Q7pZfUVjI2sCoOHRzRUf0tM9GbUSAB0GijRn98yPJUQa7F2kGeG3JO2u8i0uKONoQfp7wfsIFjFoMk21KavVvlwKoodQ_Y9fLHQ8RuAzUtHubozyfhVk5QJey635m2aYh-YIKGpsentmdWKCZG-Qw) which affect apps targeting Android 14. In order to ensure compatibility, Google has released [Play Billing Library version 6.0.1 and 5.2.1](https://notifications.google.com/g/p/ANiao5qs8DgOzTLz8Jrn4F69TdcBnkzRKx79mpToKmGv-Yoi_s6-pwFdPMefQgXTMitwEw2QSp3jAsk_48cMuhnO-H63cYAvUn4cJ6uFaoL2IRv8EmLdK2y3MUQgi170trSXyPV-paeHRtsZN9inQhAciYBkNOkWZLJpR5y5bvxHufseXjBpYuaM-hy9HgDiV0k-R2yR0nK4_s8aHGcLuuiiB9FP32R0nho0VD1_QX9SbCBDZXoZVj5OlYwdYRsVMwLfa1mYpl_lIKI3DOsHJ4l8bg). When updating your app to target Android 14, following these [migration steps](https://notifications.google.com/g/p/ANiao5rKr3ZOZ-uwXLJEIc1VuS6vkDdrJ5gOZGY0ryCd7gBdXZ-CQ3aTqzh_SVgebZx38kDaCI0m57RrY1YvEmtEJlrNKHEhBIuMdbSuewQJ_x4U0mJ-f6sxi8lkSLsl06jn5uhAAnFiYZEqXaqkerpyrP5etyWd1k2Ge-86_jhPL51qktt_mhsVd4GSKYSi4zGXgptgc3koHWZ9n5Dwr-s6yFvWUcsREbsyNks5LWF469sdxsgnYX_f59KRyHIqxkTQjuAu4Q), you will need to update your app to either of these versions of the Play Billing Library to be compatible with the recent security changes.

These changes only affect your app when it starts targeting Android 14. Users running Android 14 while your app is not targeting Android 14 are unaffected.

<img width="1431" alt="image" src="https://github.com/defold/extension-iap/assets/2209596/9647cef9-c7c7-4105-a3d6-538d53351669">

**Comment by AGulev** [comment]
Action required: Migrate to supported version of Google Play Billing Library

May 28, 2024 18:45
We are introducing changes to the lifecycle of Play Billing Library and its associated deprecation timelines. Because you currently use an older version of the library, we wanted you to be aware of new key dates you’ll need to adhere to:

By Aug 31, 2024, all new apps and updates to existing apps must use Billing Library version 6 or newer. If you need more time to update your app, you will be able to request an extension until Nov 1, 2024.

Learn more about the deprecation here.

Update before these dates to avoid a disruption in app publishing and updates. Publishing and updating apps that use Play Billing Library version lower than 6 will be blocked in Play Console on the dates mentioned above.

Next steps: More information on how to migrate to the latest version of Play Billing Library can be found on our developer website.

![image](https://github.com/defold/extension-iap/assets/2209596/40f2688a-4bde-45f6-bf9b-a77b5d1166a4)

**Comment by baochungit** [comment]
Hopefully this will process soon, I also need it for my upcoming release

**Comment by baochungit** [comment]
https://developer.android.com/google/play/billing/migrate-gpblv7#5to7
Looks like just change version to `7.0.0` is enough. Another thing to consider is the purchase order ID will be `null` for `PENDING` purchases.

**Comment by Dr-Klaus** [comment]
I can't upload new build :(
![image](https://github.com/defold/extension-iap/assets/87762110/c9a3ad31-cf69-40d7-a300-9bdd88ff9e17)
