### ISSUE TITLE
Kongregate iap support

### ISSUE THREAD

**Issue by subsoap** [defold/extension-iap#8]
https://docs.kongregate.com/docs/concepts-virtual-goods

**Comment by subsoap** [comment]
@mathiaswking Yes! Non-urgent request for more stores such as Kongregate.

**Comment by AGulev** [comment]
Kongregate.com stops accepting new games as Flash slowly disappears

https://www.theverge.com/2020/7/2/21311318/kongregate-stops-accepting-new-game-submissions-flash-discontinued-layoffs

https://www.kongregate.com/forums/1-kongregate/topics/1916387-important-kongregate-announcement
